### ISSUE TITLE
yaml copy as curl generate error code

### ISSUE THREAD

**Issue by AllenzhLi** [Huachao/vscode-restclient#748]
- REST Client Version: 0.24.4
- VSCode Version: 1.52
- OS Version: mac big sur 11.1

Steps to Reproduce:

example:
```
POST http://xxx.xxx.xxx.xxx/api/v1/alerts
Content-Type: application/x-yaml
X-Scope-OrgID: 1

template_files: {}
alertmanager_config: |
    route:
        receiver: root
        group_by:
            - '...'
        continue: false
        group_wait: 15s
        group_interval: 15s
        repeat_interval: 30m
    receivers:
        - name: root
          webhook_configs:
            - send_resolved: true
              url: http://localhost:3003/api/notifications?orgId=1&rrid=1
              max_alerts: 0
    templates: []
```
copy as curl 
```
curl --request POST \
  --url http://metric.chongqing.yf-m16.tcecqpoc.fsphere.cn/api/v1/alerts \
  --header 'content-type: applicaton/x-yaml' \
  --header 'user-agent: vscode-restclient' \
  --header 'x-scope-orgid: 1' \
  --data 'template_files: {}alertmanager_config: |route:receiver: rootgroup_by:- '\''...'\''continue: falsegroup_wait: 15sgroup_interval: 15srepeat_interval: 30mreceivers:- name: rootwebhook_configs:- send_resolved: trueurl: http://localhost:3003/api/notifications?orgId=1&rrid=1max_alerts: 0templates: []'
```
expected
```
curl -X POST 'http://metric.chongqing.yf-m16.tcecqpoc.fsphere.cn/api/v1/alerts' --header 'X-Scope-OrgID: 1' -d 'template_files: {}
alertmanager_config: |
    route:
        receiver: root
        group_by:
            - '\''...'\''
        continue: false
        group_wait: 15s
        group_interval: 15s
        repeat_interval: 30m
    receivers:
        - name: root
          webhook_configs:
            - send_resolved: true
              url: http://localhost:3003/api/notifications?orgId=1&rrid=1
              max_alerts: 0
    templates: []'
```
